# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neuer_kunde.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeuerKunde(object):
    def setupUi(self, NeuerKunde):
        NeuerKunde.setObjectName("NeuerKunde")
        NeuerKunde.setWindowModality(QtCore.Qt.ApplicationModal)
        NeuerKunde.resize(235, 231)
        self.button_ok = QtWidgets.QPushButton(NeuerKunde)
        self.button_ok.setGeometry(QtCore.QRect(20, 190, 75, 23))
        self.button_ok.setObjectName("button_ok")
        self.button_beenden = QtWidgets.QPushButton(NeuerKunde)
        self.button_beenden.setGeometry(QtCore.QRect(130, 190, 75, 23))
        self.button_beenden.setObjectName("button_beenden")
        self.label = QtWidgets.QLabel(NeuerKunde)
        self.label.setGeometry(QtCore.QRect(21, 21, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NeuerKunde)
        self.label_2.setGeometry(QtCore.QRect(21, 47, 46, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(NeuerKunde)
        self.label_3.setGeometry(QtCore.QRect(21, 73, 36, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(NeuerKunde)
        self.label_4.setGeometry(QtCore.QRect(21, 99, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(NeuerKunde)
        self.label_5.setGeometry(QtCore.QRect(21, 125, 20, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(NeuerKunde)
        self.label_6.setGeometry(QtCore.QRect(21, 151, 40, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_vorname = QtWidgets.QLineEdit(NeuerKunde)
        self.lineEdit_vorname.setGeometry(QtCore.QRect(73, 21, 133, 20))
        self.lineEdit_vorname.setObjectName("lineEdit_vorname")
        self.lineEdit_name = QtWidgets.QLineEdit(NeuerKunde)
        self.lineEdit_name.setGeometry(QtCore.QRect(73, 47, 133, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_strasse = QtWidgets.QLineEdit(NeuerKunde)
        self.lineEdit_strasse.setGeometry(QtCore.QRect(73, 73, 133, 20))
        self.lineEdit_strasse.setObjectName("lineEdit_strasse")
        self.lineEdit_plz = QtWidgets.QLineEdit(NeuerKunde)
        self.lineEdit_plz.setGeometry(QtCore.QRect(73, 99, 133, 20))
        self.lineEdit_plz.setObjectName("lineEdit_plz")
        self.lineEdit_ort = QtWidgets.QLineEdit(NeuerKunde)
        self.lineEdit_ort.setGeometry(QtCore.QRect(73, 125, 133, 20))
        self.lineEdit_ort.setObjectName("lineEdit_ort")
        self.lineEdit_telefon = QtWidgets.QLineEdit(NeuerKunde)
        self.lineEdit_telefon.setGeometry(QtCore.QRect(73, 151, 133, 20))
        self.lineEdit_telefon.setObjectName("lineEdit_telefon")

        self.retranslateUi(NeuerKunde)
        QtCore.QMetaObject.connectSlotsByName(NeuerKunde)

    def retranslateUi(self, NeuerKunde):
        _translate = QtCore.QCoreApplication.translate
        NeuerKunde.setWindowTitle(_translate("NeuerKunde", "Neuer Kunde"))
        self.button_ok.setText(_translate("NeuerKunde", "OK"))
        self.button_beenden.setText(_translate("NeuerKunde", "Beenden"))
        self.label.setText(_translate("NeuerKunde", "Vorname:"))
        self.label_2.setText(_translate("NeuerKunde", "Name:"))
        self.label_3.setText(_translate("NeuerKunde", "Straße:"))
        self.label_4.setText(_translate("NeuerKunde", "PLZ:"))
        self.label_5.setText(_translate("NeuerKunde", "Ort:"))
        self.label_6.setText(_translate("NeuerKunde", "Telefon:"))
