# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(213, 168)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_listenanzeige = QtWidgets.QPushButton(self.centralwidget)
        self.button_listenanzeige.setObjectName("button_listenanzeige")
        self.verticalLayout.addWidget(self.button_listenanzeige)
        self.button_einzelanzeige = QtWidgets.QPushButton(self.centralwidget)
        self.button_einzelanzeige.setObjectName("button_einzelanzeige")
        self.verticalLayout.addWidget(self.button_einzelanzeige)
        self.button_neuer_eintrag = QtWidgets.QPushButton(self.centralwidget)
        self.button_neuer_eintrag.setObjectName("button_neuer_eintrag")
        self.verticalLayout.addWidget(self.button_neuer_eintrag)
        self.button_suche = QtWidgets.QPushButton(self.centralwidget)
        self.button_suche.setObjectName("button_suche")
        self.verticalLayout.addWidget(self.button_suche)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Datenbank"))
        self.button_listenanzeige.setText(_translate("MainWindow", "Listenanzeige"))
        self.button_einzelanzeige.setText(_translate("MainWindow", "Einzelanzeige"))
        self.button_neuer_eintrag.setText(_translate("MainWindow", "Neuer Eintrag"))
        self.button_suche.setText(_translate("MainWindow", "Suche"))
